#!/usr/bin/env bash
#
# Yodawger
# Copyright (C) 2024  Kyle Smith
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# @describe	Manage and invoke bundled docker services in org containers
# @meta	author	Kyle Smith <kyle@kmaismith.com>
# @meta	version	0.1.0
#credit: Jeff Lieb	Contributed the name "yodawger"

# @option -e --env=`get_default_env` $SERVICE_ENV Environment to manipulate
# @flag	-A --admin	Execute command in administrative mode
# @arg	service		Name of the interface to interact with
# @arg	command		Command to invoke against the interface
# @arg	args~		Arguments to pass to the interface

set -ueo pipefail

export SYSTEM_ROOT
SYSTEM_ROOT="$(cd "$(dirname "$(readlink -f "${0}")")" ||:; pwd)"
source "${SYSTEM_ROOT}/lib/init.bash"

export SYSTEM_CONF="${SYSTEM_ROOT}/conf"
mkdir -p "${SYSTEM_CONF}"

include "<env>"
include "<setup>"

get_default_env() { env::get_default; }

#
#   INITIALIZE THE ENVIRONMENT
#

setup_docker

setup_argc

setup_envs

setup_bats

eval "$(argc --argc-eval "${0}" "${@}")"

export SYSTEM_ENV="${argc_env}" SERVICE_ENV="${argc_env}"

if [ "${argc_admin-}" = "1" ]; then
	if ! [ -f "${SYSTEM_ROOT}/bin/admin/${argc_service}" ]; then
		error "No admin commands for ${argc_service}"
	fi
	if [ "${USER}" = "root" ]; then
		"${SYSTEM_ROOT}/bin/admin/${argc_service}" \
			"${argc_command}" "${argc_args[@]}"
	else
		consented_sudo "run admin command ${0} ${@} as root" \
			"${0}" "${@}"
	fi
elif [ -f "${SYSTEM_ROOT}/bin/generic/${argc_service}" ]; then
	if [ "${USER}" = "${SYSTEM_ENV}_env" ]; then
		"${SYSTEM_ROOT}/bin/env/${argc_service}" \
			"${argc_command}" "${argc_args[@]}"
	else
		sudo -u "${SYSTEM_ENV}_env" "${0}" "${@}"
	fi
fi
