#!/usr/bin/env bash

set -ueo pipefail

# @cmd
up() {
	yo "${GENERIC_SERVICE_http}" up
}

# @cmd
reload() {
	yo "${GENERIC_SERVICE_http}" reload
}

# @cmd
list_services() {
	yo "${GENERIC_SERVICE_http}" list_services
}

# @cmd
# @arg	name
get_service() {
	yo "${GENERIC_SERVICE_http}" get_service "${argc_name}"
}

# TODO: update Caddy to implement this interface
# @cmd
# @arg	name	
# @arg	hostport
add_service() {
	yo "${GENERIC_SERVICE_http}" add_service "${argc_name}" "${argc_hostport}"
}

# @cmd
# @arg	name
remove_service() {
	yo "${GENERIC_SERVICE_http}" remove_service "${argc_name}"
}

eval "$(argc --argc-eval "${0}" "${@}")"
