#!/usr/bin/env bash

BASE_DIR="$(cd "$(dirname "${0}")" ||:; pwd)"
SCAN_DIR="${BASE_DIR}/.run"

mkdir -p "${SCAN_DIR}/.s6-svscan"
find "${BASE_DIR}" -mindepth 2 -maxdepth 2 -name "run" -type f -exec dirname {} \; | \
	xargs -r ln -sft "${SCAN_DIR}"

cat <<FINISH >"${SCAN_DIR}/.s6-svscan/finish"
#!/usr/bin/env bash

readarray -t envs < <(find "${BASE_DIR}" -maxdepth 2 -mindepth 2 -name '.run' -type d)

for env in "\${envs[@]}"; do
	if [ -p "\${env}/.s6-svscan/control" ]; then
		s6-svscanctl -t "\${env}"
	fi
done

FINISH
chmod +x "${SCAN_DIR}/.s6-svscan/finish"

exec s6-svscan "${SCAN_DIR}"
